-- MySQL Script generated by MySQL Workbench
-- 12/25/14 22:16:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ohana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ohana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ohana` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ohana` ;

-- -----------------------------------------------------
-- Table `ohana`.`Rememberance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ohana`.`Rememberance` (
  `rID` INT NOT NULL,
  `rName` VARCHAR(100) NULL,
  `rDate` DATE NULL,
  `file` LONGTEXT NULL COMMENT 'File Path\nEither video or photograph\n',
  PRIMARY KEY (`rID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ohana`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ohana`.`Users` (
  `uID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `firstName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `created` DATETIME NULL,
  `lastlogin` DATETIME NULL,
  PRIMARY KEY (`uID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ohana`.`Tree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ohana`.`Tree` (
  `treeID` INT NOT NULL AUTO_INCREMENT,
  `treeName` VARCHAR(100) NULL,
  `userID` INT NULL,
  `createOn` DATE NULL,
  PRIMARY KEY (`treeID`),
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `ohana`.`Users` (`uID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ohana`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ohana`.`Member` (
  `memberID` INT NOT NULL,
  `firstName` VARCHAR(35) NULL,
  `lastName` VARCHAR(50) NULL,
  `dateOfBirth` DATE NULL,
  `countryOfBirth` VARCHAR(20) NULL,
  `gender` VARCHAR(1) NULL,
  `treeID` INT NULL,
  `Member_memberID` INT NOT NULL,
  PRIMARY KEY (`memberID`, `Member_memberID`),
  INDEX `fk_Member_Member1_idx` (`Member_memberID` ASC),
  INDEX `fk_treeID_idx` (`treeID` ASC),
  CONSTRAINT `fk_Member_Member1`
    FOREIGN KEY (`Member_memberID`)
    REFERENCES `ohana`.`Member` (`memberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treeID`
    FOREIGN KEY (`treeID`)
    REFERENCES `ohana`.`Tree` (`treeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ohana`.`Rememberance_has_Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ohana`.`Rememberance_has_Member` (
  `Rememberance_rID` INT NOT NULL,
  `Member_memberID` INT NOT NULL,
  PRIMARY KEY (`Rememberance_rID`, `Member_memberID`),
  INDEX `fk_Rememberance_has_Member_Member1_idx` (`Member_memberID` ASC),
  INDEX `fk_Rememberance_has_Member_Rememberance_idx` (`Rememberance_rID` ASC),
  CONSTRAINT `fk_Rememberance_has_Member_Rememberance`
    FOREIGN KEY (`Rememberance_rID`)
    REFERENCES `ohana`.`Rememberance` (`rID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rememberance_has_Member_Member1`
    FOREIGN KEY (`Member_memberID`)
    REFERENCES `ohana`.`Member` (`memberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
